version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: devops_db
      MYSQL_USER: admin
      MYSQLI_PASSWORD: admin
      MYSQLI_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql # create tables on start

volumes:
  db-data:
